notitas-main/notitas/urls.py
from django.contrib import admin 
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('vehiculos/', include('vehiculos.urls'))
]

notitas-main/usuarios/urls.py
from django.urls import path
from usuarios import views

app_name = 'usuarios'
urlpatterns = [
    path('', views.registro, name='registro'),
    path('recuperacion/', views.recuperacion, name='recuperacion'),
    path('iniciar/' ,views.iniciar, name='iniciar'),
    path('cerrar' ,views.cerrar, name='cerrar'),
    path('eliminar' ,views.eliminar, name='eliminar'),
]

notitas-main/notitas/templates/plantilla.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Notitas: {% block titulo %}{% endblock titulo %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</head>

<body>
    <nav class="bg-light border navbar navbar-expand-md navbar-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'vehiculos:index' %}"><span>Notitas</span></a>
            <button aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
                data-bs-target="#navbar" data-bs-toggle="collapse" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">


        
                <ul class="navbar-nav ms-auto mt-2">
                    {% if request.session.id_usuario %}
                    <span class="nav-link">{{ request.session.id_usuario }}</span>
                    <div class="navbar-nav">
                        <a href="{% url 'usuarios:cerrar' %}" class="nav-link">Cerrar sesión </a>
                    {% else %}
                        <a href="{% url 'usuarios:iniciar' %}" class="nav-link">Iniciar sesión </a>
                        <a href="{% url 'usuarios:registro' %}" class="nav-link">Registrarse</a>
                        <a href="{% url 'usuarios:eliminar' %}" class="nav-link">Eliminar usuario</a>
                    {% endif %}

                </ul>
   
            </div>
        </div>
    </nav>
        {% block contenido %}{% endblock contenido %}
    </div>
</body>

</html>